server:
  port: 8001
  servlet:
    context-path: /register

spring:
  application:
    name: FEBS-Register
  security:
    user:
      name: febs
      password: 123456

eureka:
  instance:
    hostname: localhost # 指定了Eureka服务端的地
  client:
    register-with-eureka: false # 表示是否将服务注册到Eureka服务端
    fetch-registry: false # 表示是否从Eureka服务端获取服务信息
    instance-info-replication-interval-seconds: 30 # 微服务更新实例信息的变化到Eureka服务端的间隔时间
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/ # 指定Eureka服务端的地址

